### ISSUE TITLE
Pooling Library: Objects remain inactive when leaving the pool.

### ISSUE THREAD

**Issue by SinyavtsevIlya** [Leopotam/LeopotamGroupLibraryUnity#7]
It's strange, but in PoolContainer there is no `SetActive(true)` when we call `Get()` and when the object `IsNew` there is `SetActive(false)` for some reason. 

Thus the objects remain off. Fixed it manually - seems like It works ok.

**Comment by Leopotam** [comment]
Well, how it works.
* `Get` request. Pool manager gives you new disabled instance. Why disabled? For additional initialization on your side and enable only after it. For example, if you will get already enabled visual prefab instance and only then change transform position - you will see strange "jump" from last visible point to new one. Its why you should set new parameters to instance and only then enable it.
* Recycle() request. Its some sort of protection programming - automatic disabling of instance, nothing more.

**Comment by Leopotam** [comment]
@SinyavtsevIlya is it clear to you?

**Comment by SinyavtsevIlya** [comment]
Now it's clear, although it's a bit tricky :) (may be it's a good idea to document it)
One more question:
- Why would I need to override `PoolObject`? I mean is there some special cases for that?

**Comment by Leopotam** [comment]
> Why would I need to override PoolObject?

Well, you can use your custom `MonoBehaviour` with implementation of `IPoolObject` with custom logic - no need to keep additional `PoolObject` component. Its optional behaviour.

**Comment by Leopotam** [comment]
@SinyavtsevIlya is this issue still actual or can be closed?
